use service instead of plist
koekeishiya/homebrew-formulae pull request #25
Opened 2023-02-06 07:47 UTC by glepnir

recently homebrew had deprecated the `plist_options` suggest use the `service.require_root` instead . I am not familiar the homebrew just read the doc of it then write this.  not sure is correct . thanks

2023-02-09 18:33 UTC, mvllow commented
I've never installed a formulae locally so may be an issue on my end but I'm getting the following error when cloning this PR and running `brew install ./yabai.rb`:

```sh
Service#environment_variables expects a hash
Error: Failed to install service files
Error: Service#environment_variables expects a hash
```

2023-02-09 19:25 UTC, mvllow requested changes
A lot of this was discovered through trial and error so some suggestions may be overkill or unnecessary but this does work when installing locally via `brew install ./yabai.rb`. Hope this helps!

2023-02-09 19:25 UTC, mvllow commented on yabai.rb
> +    environment_variables HOMEBREW_PREFIX/"bin:/usr/bin:/bin:/usr/sbin:/sbin"
Saw this used in a few other formulae and it seems to fix the error.

```suggestion
    environment_variables PATH: "#{HOMEBREW_PREFIX}/bin:/usr/bin:/bin:/usr/sbin:/sbin"
```

2023-02-09 19:25 UTC, mvllow commented on yabai.rb
> +    err_log_path var"/log/yabai/yabai.err.log"
Looks like this option is called `error_log_path`.
https://docs.brew.sh/Formula-Cookbook#page

```suggestion
    error_log_path "#{var}/log/yabai/yabai.err.log"
```

2023-02-09 19:25 UTC, mvllow commented on yabai.rb
> +    run opt_bin/"yabai"
This could probably be ignored, just suggesting for consistency.

```suggestion
    run "#{opt_bin}/yabai"
```

2023-02-14 18:48 UTC, mvllow commented on yabai.rb
> +    require_root true
Does this need root?

```suggestion
```

2023-02-14 18:48 UTC, mvllow commented on yabai.rb
> +    interval 30
> seem like this only request when run_type is set to interval

Suggestion per @hunterliao29 on #27 

```suggestion
```

2023-02-17 12:21 UTC, CKolkey commented on yabai.rb
> +    log_path var/"log/yabai/yabai.out.log"
Ruby would parse this as `var / "...string content"`, so the division operator. Concatenation would be `var + "/....", but interpolating it like you did is ideal.

2023-03-22 18:17 UTC, koekeishiya commented
Track #31 instead.

2023-03-22 18:17 UTC, closed without merging